### ISSUE TITLE
Missing endings models

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/the-accountant-backend#2]

**Comment by larjohn** [comment]
Consequences added to database

**Comment by skarampatakis** [comment]
Could push the update on the feature/analytics branch? Current master was in sync with original and not your changes.

**Comment by skarampatakis** [comment]
Ooopps, that goes on the accountant repo, sry for the confusion.

**Comment by larjohn** [comment]
I moved the commit to the mentioned branch
