### ISSUE TITLE
In case of undo or play again the record is not created

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/the-accountant-backend#3]
When you finish the game you can either undo your last step, or play again from start. It seems that the new history does get saved.

**Comment by larjohn** [comment]
History is saved only when the game finishes. In that case (undo) the new record's session_id will be the same as the previous record

**Comment by skarampatakis** [comment]
I agree but none is created. Only the first. Even if I play mutliple times the game, I have only one record on the database.

**Comment by larjohn** [comment]
Have you finished the subsequent games? Can you monitor your network
activity when the game over banner pops up?




*ʌἁɀɑƿѻѕ ɪɷɑⱴⱴἱɗʜѕ*

2017-07-16 9:39 GMT+03:00 Sotirios Karampatakis <notifications@github.com>:

**Comment by skarampatakis** [comment]
Yes. The post was created on the first attemp but never fired on the second.

**Comment by skarampatakis** [comment]
played again from the public server and seems to be working as supposed. A new record was created with the same session_id. 

On the case of a new game a new session id is created and a new record on the database. So I think we can close this issue.
