### ISSUE TITLE
IP recorded is always the localhost

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/the-accountant-backend#4]
the IP that gets recorded on the database is always the localhost. Does this has to do with proxy settings?

**Comment by larjohn** [comment]
Aren't you playing the game on the same computer? In an event context this
will always be the case: all the participants will share the same IP
address, behind a router. I think IP address is a very bad way to keep
record of people. We 'd better rely on session_id's or make some login
system.




*ʌἁɀɑƿѻѕ ɪɷɑⱴⱴἱɗʜѕ*

2017-07-16 10:28 GMT+03:00 Sotirios Karampatakis <notifications@github.com>:

**Comment by skarampatakis** [comment]
No, the first time I played through the servers IP and the second from my local PC on the temp public server 

http://bioweb.math.auth.gr/accountant/

I agree with the use of session_id instead of IPs. So we could perhaps drop IP recording and keep the session id.
